name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          pip3 install snowflake-cli-labs
          
      - name: Add pip binaries to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Verify snowcli installation
        run: snowcli --version

      - name: Set up Snowflake config
        run: |
          snowcli config add --name github-ci \
            --account ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            --user ${{ secrets.SNOWFLAKE_USER }} \
            --password ${{ secrets.SNOWFLAKE_PASSWORD }} \
            --role ${{ secrets.SNOWFLAKE_ROLE }} \
            --warehouse ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
            --database ${{ secrets.SNOWFLAKE_DATABASE }} \
            --schema ${{ secrets.SNOWFLAKE_SCHEMA }}

      - name: Deploy SQL to Snowflake
        run: |
          snowcli sql run -f ./sql/deploy.sql --connection github-ci
