name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          sudo apt-get update
          pip install snowflake-cli-labs

      - name: Set up Snowflake config
        run: |
          snowcli config add --name github-ci \
            --account ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            --user ${{ secrets.SNOWFLAKE_USER }} \
            --password ${{ secrets.SNOWFLAKE_PASSWORD }} \
            --role ${{ secrets.SNOWFLAKE_ROLE }} \
            --warehouse ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
            --database ${{ secrets.SNOWFLAKE_DATABASE }} \
            --schema ${{ secrets.SNOWFLAKE_SCHEMA }}

      - name: Deploy SQL to Snowflake
        run: |
          snowcli sql run -f ./sql/deploy.sql --connection github-ci
