name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip curl

      - name: Pre-check for SnowSQL install
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip libncurses6
          mkdir -p $HOME/snowflake/snowsql/bin
 

      - name: Install SnowSQL v1.2.24
        run: |
          set -x
          mkdir -p $HOME/snowflake/snowsql
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24-linux_x86_64.bash
          chmod +x snowsql-1.2.24-linux_x86_64.bash
          ./snowsql-1.2.24-linux_x86_64.bash -y -d $HOME/snowflake/snowsql || true
          echo "========= INSTALL LOG ========="
          cat $HOME/snowflake/snowsql/install.log || echo "No install.log found"
          echo "========= BINARY PATH ========="
          ls -l $HOME/snowflake/snowsql/bin
          echo "$HOME/snowflake/snowsql/bin" >> $GITHUB_PATH




      - name: Verify SnowSQL installation
        run: |
          snowsql --version

      - name: Run deploy.sql on Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          export PATH=$HOME/snowflake/snowsql/bin:$PATH
          snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -s $SNOWFLAKE_SCHEMA -f ./sql/deploy.sql
