name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SnowSQL 1.4.1
        run: |
          set -x
          mkdir -p $HOME/snowflake/snowsql
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowsql-1.4.1-linux_x86_64.bash
          chmod +x snowsql-1.4.1-linux_x86_64.bash
          SNOWSQL_DEST=$HOME/snowflake/snowsql SNOWSQL_LOGIN_SHELL=/dev/null ./snowsql-1.4.1-linux_x86_64.bash -y
          echo "$HOME/snowflake/snowsql/bin" >> $GITHUB_PATH

      - name: Verify SnowSQL installation
        run: |
          snowsql -v
          which snowsql
          snowsql --help

      - name: Run deploy.sql on Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          export PATH=$HOME/snowflake/snowsql/bin:$PATH
          snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD \
            -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -s $SNOWFLAKE_SCHEMA \
            -f ./sql/deploy.sql
