name: Snowflake Deployment via SnowSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          sudo apt-get install unzip
          wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.21-linux_x86_64.bash
          bash snowsql-1.2.21-linux_x86_64.bash

      - name: Run deploy.sql in Snowflake
        run: |
          ~/.snowsql/snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
                             -u ${{ secrets.SNOWFLAKE_USER }} \
                             -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
                             -r ${{ secrets.SNOWFLAKE_ROLE }} \
                             -d ${{ secrets.SNOWFLAKE_DATABASE }} \
                             -s ${{ secrets.SNOWFLAKE_SCHEMA }} \
                             -w ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
                             -f sql/deploy.sql
